[package]
name = "qr2text"
version = "0.0.1"
description = "Render a QR code directly in the terminal"
license = "MIT"
repository = "https://github.com/wapm-packages/qr2text"

[[module]]
name = "qr2text"
source = "target/wasm32-wasi/release/qr2text.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "qr2text"
module = "qr2text"
